# Site settings
title: Leslie Reyes
email: lesliereyes@lesliereyes.me
description: > # this means to ignore newlines until "baseurl:"
  Hi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lesliereyes.com" # the base hostname & protocol for your site
twitter_username: lesliereyees
github_username:  ldreyes

# Build settings
markdown: kramdown
